# config/news_items.yml - 最新情報の設定ファイル

# 最新情報の一覧
news_items:
  - title: "🎉 新年のご挨拶"
    content: "2024年も引き続き、皆様の健康とリラクゼーションをサポートさせていただきます。本年もよろしくお願いいたします。"
    date: "2024/01/01"
    category: "お知らせ"
    priority: 1

  - title: "📅 年末年始営業時間のお知らせ"
    content: "12月30日〜1月3日は休業とさせていただきます。1月4日より通常営業いたします。"
    date: "2023/12/20"
    category: "営業時間"
    priority: 2

  - title: "🌟 新コース追加のお知らせ"
    content: "お客様からのご要望により、80分コースを新たに追加いたしました。より深いリラクゼーションをお楽しみいただけます。"
    date: "2023/12/15"
    category: "サービス"
    priority: 3

  - title: "💆‍♀️ 感染症対策の継続"
    content: "引き続き、消毒・換気・マスク着用等の感染症対策を徹底して営業いたします。ご安心してお越しください。"
    date: "2023/12/10"
    category: "お知らせ"
    priority: 4

# カテゴリの設定
categories:
  - name: "お知らせ"
    color: "#FF6B35"
    icon: "📢"
  
  - name: "営業時間"
    color: "#4CAF50"
    icon: "🕒"
  
  - name: "サービス"
    color: "#2196F3"
    icon: "🌟"
  
  - name: "キャンペーン"
    color: "#FF9800"
    icon: "🎁"
  
  - name: "メンテナンス"
    color: "#9C27B0"
    icon: "🔧"
